"""Mirror the per-isotope shards and the dataset card to Hugging Face.

`catalog.json` has claimed since the endfb-8.0 release that the shards are
"also mirrored on Hugging Face (gerchowl/nucl-parquet-data)", but nothing in the
repo ever pushed them — the mirror was maintained by hand. That is how it came
to carry `license: mit` over ENDF/B-VIII.0, a US Government work nobody here is
in a position to relicense (#234).

This makes the mirror a build artifact: the card is generated from
`data/licenses.toml` so the published licence can no longer drift from the
compliance record, and `release-data.yml` calls it on every data tag.

Requires HF_TOKEN with write access to the dataset repo.

Usage:
    nix develop -c .venv/bin/python scripts/sync_huggingface.py --dry-run
    HF_TOKEN=... nix develop -c .venv/bin/python scripts/sync_huggingface.py
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import tomllib
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

ROOT = Path(__file__).parent.parent
REPO_ID = "gerchowl/nucl-parquet-data"

# Which library's shards the mirror carries, and therefore whose licence governs
# the dataset card.
MIRRORED_LIBRARY = "endfb-8_0"


def build_card(data_dir: Path) -> str:
    """Generate the dataset card, with licence taken from licenses.toml.

    Deriving it rather than hand-writing it is the point: a wrong licence on a
    public mirror is a compliance problem, and hand-maintained metadata drifts.
    """
    licenses = tomllib.loads((data_dir / "licenses.toml").read_text())
    lic = licenses["libraries"][MIRRORED_LIBRARY]
    catalog = json.loads((data_dir / "catalog.json").read_text())

    return f"""---
license: other
license_name: us-government-work
license_link: {lic["terms_url"]}
tags:
  - nuclear-data
  - cross-sections
  - neutron
  - endf
pretty_name: nucl-parquet data (NJOY-processed neutron cross sections)
---

# nucl-parquet-data

Per-isotope neutron cross-section shards for
[nucl-parquet](https://github.com/exoma-ch/nucl-parquet), hosted so consumers can
**range-fetch one isotope at a time** rather than download a monolith.

Data version: `{catalog["data_version"]}`

## Licensing

**{lic["license"]}**

{lic["notes"]}

MIT covers the nucl-parquet *code and conversion*, not the bundled evaluated
data. Per-library terms are recorded in
[`data/licenses.toml`](https://github.com/exoma-ch/nucl-parquet/blob/main/data/licenses.toml).

Cite: {lic["citation"]}

Custodian: {lic["custodian"]}

---

*This card is generated by `scripts/sync_huggingface.py` from
`data/licenses.toml`. Edit it there, not here — a hand edit will be overwritten
on the next data release.*
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", type=Path, default=ROOT / "data")
    ap.add_argument("--repo-id", default=REPO_ID)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument(
        "--card-only",
        action="store_true",
        help="push the dataset card but not the shards",
    )
    args = ap.parse_args()

    card = build_card(args.data_dir)
    if args.dry_run:
        print(card)
        logger.info("dry run — nothing uploaded")
        return

    token = os.environ.get("HF_TOKEN")
    if not token:
        logger.error("HF_TOKEN is not set")
        raise SystemExit(1)

    from huggingface_hub import HfApi

    api = HfApi(token=token)
    api.upload_file(
        path_or_fileobj=card.encode(),
        path_in_repo="README.md",
        repo_id=args.repo_id,
        repo_type="dataset",
        commit_message="chore: regenerate dataset card from licenses.toml",
    )
    logger.info("card pushed to %s", args.repo_id)

    if args.card_only:
        return

    shard_dir = args.data_dir / "endfb-8.0" / "xs"
    if not shard_dir.exists():
        logger.warning("no shards at %s — card only", shard_dir)
        return
    api.upload_folder(
        folder_path=str(shard_dir),
        path_in_repo="neutron",
        repo_id=args.repo_id,
        repo_type="dataset",
        commit_message="chore: sync neutron shards",
    )
    logger.info("shards pushed from %s", shard_dir)


if __name__ == "__main__":
    main()
